version: '3'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: koupang_test
      POSTGRES_USER: koupang_test
      POSTGRES_PASSWORD: koupang_test
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
